# C/C++ CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details
#
# MAINTAINER Kirill Scherba <kirill@scherba.ru>
#
# Versin 0.0.1
#

version: 2
jobs:

  # direct-download:
  #   docker: # run the steps with Docker
  #     - image: gitlab.ksproject.org:5000/ci/ubuntu_teonet
  #   steps:
  #     - checkout
  #     # Add to direct download list
  #     - run: curl -vvf -X PUT -u$CI_BINTRAY_USER:$CI_BINTRAY_API_KEY -H "Content-Type:application/json" -d '{"list_in_downloads":true}' "https://api.bintray.com/file_metadata/teonet-co/u/pool/main/"$PACKET_NAME"/"$PACKAGE_NAME"_wheezy.deb"
  #     - run: echo ""
      
  #     # Add to direct download list
  #     - run: curl -vvf -X PUT -u$CI_BINTRAY_USER:$CI_BINTRAY_API_KEY -H "Content-Type:application/json" -d '{"list_in_downloads":true}' "https://api.bintray.com/file_metadata/teonet-co/u/pool/main/"$PACKET_NAME"/"$PACKAGE_NAME"_bionic.deb"
  #     - run: echo ""


  un-tagged-build-ubuntu:
    docker: # run the steps with Docker
      - image: teonet-co-docker-d.bintray.io/ci/ubuntu_teonet # gitlab.ksproject.org:5000/ci/ubuntu_teonet
    steps:
      - checkout
      - run: git submodule update --init --recursive

      # show current variables
      - run: echo $CIRCLE_PROJECT_REPONAME
      - run: echo $CIRCLE_BRANCH
      - run: echo $CIRCLE_TAG
      - run: echo $CI_BUILD_REF_BT

      # Install dependences
      #- run: sh/build-ubuntu.sh
      #- run: sudo apt-get install -y libcunit1-dev cpputest

      # Make
      - run: ./autogen.sh --prefix=/usr
      - run: make

      # Test
      #- run: app/teovpn -?
      - run: make test
      
      # Buid binary deb package
      #- run: git clone git@github.com:teonet-co/ci-build.git
      - run: ci-build/make_package deb

#      # build the application image
#      - run: docker build --no-cache -t $CIRCLE_PROJECT_REPONAME -f docker/Dockerfile .
#
#      # Check created image
#      - run: docker run -it --rm --name $CIRCLE_PROJECT_REPONAME $CIRCLE_PROJECT_REPONAME node . -?
#
#      # This is place for run unit tests from docker container


  un-tagged-build-centos:
    docker: # run the steps with Docker
      - image: teonet-co-docker-d.bintray.io/ci/ubuntu_centos # gitlab.ksproject.org:5000/ci/centos_teonet
    steps:
      - checkout
      - run: git submodule update --init --recursive

      # show current variables
      - run: echo $CIRCLE_PROJECT_REPONAME
      - run: echo $CIRCLE_BRANCH
      - run: echo $CIRCLE_TAG

      # Install dependences
      #- run: sh/build-centos.sh
      # Make
      - run: ./autogen.sh --prefix=/usr
      - run: make
      # Test
      #- run: app/teovpn -?
      - run: make test


  tagged-build-ubuntu:
    docker: # run the steps with Docker
      - image: teonet-co-docker-d.bintray.io/ci/ubuntu_teonet
    steps:
      - checkout
      - run: git submodule update --init --recursive

      # show current variables
      - run: echo $CIRCLE_PROJECT_REPONAME
      - run: echo $CIRCLE_BRANCH
      - run: echo $CIRCLE_TAG

      # Install dependences
      #- run: sh/build-ubuntu.sh
      # Make
      - run: ./autogen.sh --prefix=/usr
      - run: make
      # Test
      #- run: app/teovpn -?
      - run: make test

      # Build DEB package and upload it to repository
      #- run: sh/make_package deb


  tagged-build-centos:
    docker: # run the steps with Docker
      - image: teonet-co-docker-d.bintray.io/ci/centos_teonet
    steps:
      - checkout
      - run: git submodule update --init --recursive

      # show current variables
      - run: echo $CIRCLE_PROJECT_REPONAME
      - run: echo $CIRCLE_BRANCH
      - run: echo $CIRCLE_TAG

      # Install dependences
      #- run: sh/build-centos.sh
      # Make
      - run: ./autogen.sh --prefix=/usr
      - run: make
      # Test
      #- run: app/teovpn -?
      - run: make test

      # Build RPM package and upload it to repository
      #- run: sh/make_package yum


  tagged-build-opensuse:
    docker: # run the steps with Docker
      - image: teonet-co-docker-d.bintray.io/ci/opensuse_teonet
    steps:
      - checkout
      - run: git submodule update --init --recursive

      # show current variables
      - run: echo $CIRCLE_PROJECT_REPONAME
      - run: echo $CIRCLE_BRANCH
      - run: echo $CIRCLE_TAG

      # Install dependences
      #- run: sh/build-opensuse.sh
      # Make
      - run: ./autogen.sh --prefix=/usr
      - run: make
      # Test
      #- run: app/teovpn -?
      - run: make test

      # Build RPM package and upload it to repository
      - run: sh/make_package zyp


  # tagged-build-docker:
  #   #machine: true      
  #   machine: #true
  #     docker_layer_caching: true    # default - false
  #   steps:
  #     - checkout  
  #     # build the application image
  #     - run: sudo sysctl -w net.ipv4.ip_forward=1
  #     - run: docker build --no-cache -t $CIRCLE_PROJECT_REPONAME -f sh/Dockerfile .

  #     # Check created image
  #     - run: docker run -it --rm --name $CIRCLE_PROJECT_REPONAME $CIRCLE_PROJECT_REPONAME teovpn -?

  #     # deploy the image
  #     - run: docker tag $CIRCLE_PROJECT_REPONAME gitlab.ksproject.org:5000/teonet/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
  #     - run: docker push gitlab.ksproject.org:5000/teonet/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
  #     #
  #     - run: docker tag $CIRCLE_PROJECT_REPONAME gitlab.ksproject.org:5000/teonet/$CIRCLE_PROJECT_REPONAME:latest
  #     - run: docker push gitlab.ksproject.org:5000/teonet/$CIRCLE_PROJECT_REPONAME:latest


  testing: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/mern-starter # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
       - run: echo Run tests of $CIRCLE_PROJECT_REPONAME project
#      - checkout # special step to check out source code to working directory
#      - run:
#          name: update-npm
#          command: 'sudo npm install -g npm@latest'
#      - restore_cache: # special step to restore the dependency cache
#          key: dependency-cache-{{ checksum "package.json" }}
#      - run:
#          name: install-npm-wee
#          command: npm install
#      - save_cache: # special step to save the dependency cache
#          key: dependency-cache-{{ checksum "package.json" }}
#          paths:
#            - ./node_modules
#      - run: # run tests
#          name: test
#          command: npm test


workflows:
  version: 2  
  un-tagged:
    jobs:
      - testing:
          filters:
            branches:
              only: master
            tags:
              ignore: /^v.*/

      - un-tagged-build-ubuntu:
          context: CI_BUILD
          requires:
            - testing
          filters:
            branches:
              only: master
            tags:
              ignore: /^v.*/

#      - un-tagged-build-centos:
#          requires:
#            - testing
#          filters:
#            tags:
#              ignore: /^v.*/


  # skipped:
  #   jobs:
  #     - testing:
  #         filters:
  #           branches:
  #             only: /~master/
  #           tags:
  #             ignore: /^v.*/

  tagged:
    jobs:
      - testing:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - tagged-build-ubuntu:
          context: CI_BUILD
          requires:
            - testing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

#      - tagged-build-centos:
#          requires:
#            - testing
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /^v.*/

#      - tagged-build-opensuse:
#          requires:
#            - testing
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /^v.*/

#       - tagged-build-docker:
#           requires:
#             - tagged-build-ubuntu
# #            - tagged-build-centos
# #            - tagged-build-opensuse
#           filters:
#             branches:
#               ignore: /.*/
#             tags:
#               only: /^v.*/
